### PR TITLE
#12: fix incorrectly checked value of request parameters

### LINKED ISSUE #12: Cannot resize to 0 instances
Hi All,

If target size of the region instance group is 0, resize fails with bad request, since `?size=0` parameter is removed

The following check should be `if v is not None` currently it is `if v` and 0 equals to False in Python.

https://github.com/googleapis/python-compute/blob/16e7294cd536af9a8bf8e4e99219a883339aa955/google/cloud/compute_v1/services/region_instance_group_managers/transports/rest.py#L1339

### PR DESCRIPTION
**Pull request by igor-solomatov**
Thank you for opening a Pull Request! Before submitting your PR, there are a few things you can do to make sure it goes smoothly:
- [x] Make sure to open an issue as a [bug/issue](https://github.com/googleapis/python-compute/issues/new/choose) before writing your code!  That way we can discuss the change, evaluate designs, and agree on the general idea
- [x] Ensure the tests and linter pass
- [x] Code coverage does not decrease (if any source code was changed)
- [x] Appropriate docs were updated (if necessary)

Fixes #12  🦕

### CODE REVIEW

**Comment by igor-solomatov** [comment]
@googlebot I signed it!

**Comment by busunkim96** [comment]
@igor-solomatov Thanks for opening a PR! This library is actually generated from the the discovery representation of the API (see https://github.com/googleapis/googleapis-discovery/tree/master/google/cloud/compute/v1), so we would make any fixes to the source templates: https://github.com/googleapis/gapic-generator-python/tree/master/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/transports

@yon-mg @vam-google Could you take a look at this PR and #12?

**Comment by igor-solomatov** [comment]
I saw it is an autogen, but could not find a source of it.
Yep, this line is a problem:
https://github.com/googleapis/gapic-generator-python/blob/944136c5ed11af03b1960ac1f0db9f4d0733b381/gapic/templates/%25namespace/%25name_%25version/%25sub/services/%25service/transports/rest.py.j2#L194

**Comment by yon-mg** [comment]
This is will be addressed in an upcoming pr to the generator that also addresses grpc transcoding in general.

**Comment by parthea** [comment]
Hi @yon-mg, please could you add an update to #12 ?

**Comment by parthea** [comment]
I'm going to close this PR as it is touching auto-generated files. Let's continue the discussion in #12 .

**Pull request closed without merging**
