### PR TITLE
chore: assign googleapis/api-compute as codeowners

### PR DESCRIPTION
**Pull request by parthea**
Assign @googleapis/api-compute as codeowners.

This is required for https://github.com/googleapis/synthtool/pull/1201

### CODE REVIEW

**Comment by parthea** [comment]
@m-strzelczyk Please use [this link](https://github.com/orgs/googleapis/teams/api-compute/members) to join the team.

**Comment by busunkim96** [comment]
It looks like `api-compute` is teamsync managed so folks who join manually will get removed. @bcoe Could you add the Compute folks to the group that's synced to `api-compute`?

**Comment by bcoe** [comment]
@busunkim96 @parthea reach out in chat Monday, and I'll make sure the right folks are in the mdb group.

**Review by busunkim96 — APPROVED** [review]

**Review by bcoe — APPROVED** [review]

**Comment by bcoe** [comment]
this team shoudl have the appropriate folks now, let me know if there are any issues.

**Pull request merged**
